[tool.poetry]
name = "mmfm"
version = "0.1.0"
description = ""
authors = ["dbb"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
code-loader = "^1.0.145"
code-loader-helpers = "^1.0.20"
torchvision = "0.16.0"
google-cloud = "^0.34.0"
google-auth = "^2.39.0"
google-cloud-storage = "^3.1.0"
py-readability-metrics = "^1.4.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
test = "leap_binder: check_integration"
custom_test = "leap_custom_test: check_custom_integration"
